### ISSUE TITLE
Template is wrong for rsyslog 7+

### ISSUE THREAD

**Issue by noahsw** [jakshi/loggly_rsyslog_ng#2]
According to https://www.loggly.com/docs/rsyslog-manual-configuration/, rsyslog 7+ should be using a slightly different format:
```
template(name="LogglyFormat" type="string"
 string="<%pri%>%protocol-version% %timestamp:::date-rfc3339% %HOSTNAME% %app-name% %procid% %msgid% [TOKEN@41058 tag=\"TAG\"] %msg%\n")

# Send messages to Loggly over TCP using the template.
action(type="omfwd" protocol="tcp" target="logs-01.loggly.com" port="514" template="LogglyFormat")
```

This cookbook only uses the rsyslog 6 format:
```
$template LogglyFormat,"<%pri%>%protocol-version% %timestamp:::date-rfc3339% %HOSTNAME% %app-name% %procid% %msgid% [TOKEN@41058 tag=\"TAG\"] %msg%\n"

# Send messages to Loggly over TCP using the template.
*.* @@logs-01.loggly.com:514;LogglyFormat
```

**Comment by jakshi** [comment]
Hello @noahsw 

I did it because rsyslog 7+ supports rsyslog 6 format, but vice versa is not true.

In future I can check for rsyslog version and generate different configs for rsyslog 6 and rsyslog 7+.

Anyhow - if it's considered an urgent feature - I accept pull requests.

Kindest Regards.

**Comment by jakshi** [comment]
Hello @noahsw 
I rewrote cookbook to use rsyslog 7+ config format if there's rsyslog 7+ installed.

So I consider this issue as resolved.
